# Personalize your website info here
title:            Elizabeth Swanson
tagline:          'Professional Website for Elizabeth Swanson'
description:      'Website and Blog for Elizabeth Swanson'
url:              http://easwanson.github.io
author:
  name:           'Elizabeth Swanson'
  url:            https://twitter.com/easwanson2005

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
